<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="LAPTOP-K171VAOP" failures="1" tests="1" name="Accounts Page Test(failed)" time="16.493" errors="0" timestamp="2022-04-09T13:47:58 IST">
  <testcase classname="com.ba.democart.tests.AccountsPageTest" name="accPageHeaderTest" time="1.139">
    <failure type="java.lang.AssertionError" message="expected [Your Store11] but found [Your Store]">
      <![CDATA[java.lang.AssertionError: expected [Your Store11] but found [Your Store]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.ba.democart.tests.AccountsPageTest.accPageHeaderTest(AccountsPageTest.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- accPageHeaderTest -->
  <testcase classname="com.ba.democart.tests.AccountsPageTest" name="selectProductTest" time="0.0">
    <ignored/>
  </testcase> <!-- selectProductTest -->
  <testcase classname="com.ba.democart.tests.AccountsPageTest" name="accPageTitleTest" time="0.0">
    <ignored/>
  </testcase> <!-- accPageTitleTest -->
  <testcase classname="com.ba.democart.tests.AccountsPageTest" name="logoutLinkExistTest" time="0.0">
    <ignored/>
  </testcase> <!-- logoutLinkExistTest -->
  <testcase classname="com.ba.democart.tests.AccountsPageTest" name="searchTest" time="0.0">
    <ignored/>
  </testcase> <!-- searchTest -->
  <testcase classname="com.ba.democart.tests.AccountsPageTest" name="accSectionListTest" time="0.0">
    <ignored/>
  </testcase> <!-- accSectionListTest -->
</testsuite> <!-- Accounts Page Test(failed) -->
